# Site
name: "Electric Sheep"
description: "Electric Sheep is a blog about technology, privacy, and freedom."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-sitemap

postcss:
  cache: false

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
